### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by Selur** [sekrit-twc/EdgeFixer#11]
Would be nice if this could also be compiled on Linux.

**Comment by sekrit-twc** [comment]
`gcc *.c *.cpp -o edgefixer.so`

**Comment by Selur** [comment]
That stops for me with:
```
EdgeFixer/avsplugin.cpp:2:10: fatal error: Windows.h: No such file or directory
 #include <Windows.h>
```
just using
```
gcc *.c -o libedgefixer.so
```
and leaving out the avsplugin.cpp I get:
```
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
/tmp/cc7dIKFW.o: In function `edgefixer_process_edge_b':
edgefixer.c:(.text+0x121): undefined reference to `lrintf'
edgefixer.c:(.text+0x2ed): undefined reference to `lrintf'
/tmp/cc7dIKFW.o: In function `edgefixer_process_edge_w':
edgefixer.c:(.text+0x450): undefined reference to `lrint'
edgefixer.c:(.text+0x647): undefined reference to `lrint'
collect2: error: ld returned 1 exit status
```
My default LFLAGS and CFLAGS are:
LFLAGS: `-L/home/selur/opt/vapoursynth/lib`
CFLAGS: `-pipe -O3 -Wno-attributes -fPIC -fvisibility=hidden -fno-strict-aliasing -I/home/selur/opt/vapoursynth/include/vapoursynth -I/home/selur/opt/vapoursynth/include -I/usr/include/compute`
which work fine with the other Vapoursynth plugins I compile.

Cu Selur

**Comment by sekrit-twc** [comment]
`-lm -shared`

**Comment by 4re** [comment]
`EdgeFixer/edgefixer.c EdgeFixer/vsplugin.c` too

**Comment by Selur** [comment]
That works thanks :)

**Comment by sekrit-twc** [comment]
In conclusion:

    cd EdgeFixer; gcc -shared -o edgefixer.so edgefixer.c vsplugin.c -lm
