### ISSUE TITLE
Doesn't fix top line

### ISSUE THREAD

**Issue by Z0nder** [sekrit-twc/EdgeFixer#6]
Doesn't fix 1px top line:
https://i.imgur.com/M5hbk5C.png  (x4 zoom, frame starts below white line).

It fixed 3px at left side (better than any other plugin I tried).

**Comment by sekrit-twc** [comment]
Please share an original-resolution image. EdgeFixer can not fix solid white lines.

**Comment by Z0nder** [comment]
I meant that "white" in screenshot is program's window. Line is black.
https://i.imgur.com/kB1FG5h.png

**Comment by sekrit-twc** [comment]
EdgeFixer can not fix the top line in kB1FG5h.png because it contains no information (solid black).
