### ISSUE TITLE
wrong path writing.

### ISSUE THREAD

**Issue by fuchanghao** [sekrit-twc/EdgeFixer#7]
Visual Studio 2019 16.1.6.

$(ProjectDir)..\AviSynthPlus\avs_core\include 

will be linked to

EdgeFixer\EdgeFixer\..\AviSynthPlus\avs_core\include

The right writing should be

$(SolutionDir)AviSynthPlus\avs_core\include

**Comment by sekrit-twc** [comment]
$(ProjectDir) implicitly has a "\", so it is EdgeFixer\EdgeFixer\..\AviSynthPlus, which is correct.

**Comment by fuchanghao** [comment]
> 
> 
> $(ProjectDir) implicitly has a "\", so it is EdgeFixer\EdgeFixer\..\AviSynthPlus, which is correct.

It's EdgeFixer\EdgeFixer\..\AviSynthPlus.

**Comment by sekrit-twc** [comment]
What is the issue then?
