### ISSUE TITLE
Having problems with the r1

### ISSUE THREAD

**Issue by Selur** [sekrit-twc/EdgeFixer#8]
using:
```
# Imports
import vapoursynth as vs
core = vs.get_core()
# Loading Plugins
core.std.LoadPlugin(path="I:/Hybrid/64bit/vsfilters/MiscFilter/EdgeFixer.dll")
core.std.LoadPlugin(path="I:/Hybrid/64bit/vsfilters/SourceFilter/FFMS2/ffms2k.dll")
# Loading source using FFMS2K
clip = core.ffms2.Source(source="F:/TESTCL~1/files/test.avi",cachefile="E:/Temp/avi_078c37f69bb356e7b5fa040c71584c40_853323747.ffindex",format=vs.YUV420P8,alpha=False)
# making sure input color matrix is set as 470bg
clip = core.resize.Point(clip, matrix_in_s="470bg",range_s="limited")
# making sure frame rate is set to 25
clip = core.std.AssumeFPS(clip, fpsnum=25, fpsden=1)
# Setting color range to TV (limited) range.
clip = core.std.SetFrameProp(clip=clip, prop="_ColorRange", intval=1)
# fixing bright and dark line artifacts near the border of an image using EdgeFixer
clip = core.edgefixer.Continuity(clip=clip,left=10,radius=10)
# Output
clip.set_output()
```
I get:
```
Failed to evaluate the script:
Python exception: Failed to load I:/Hybrid/64bit/vsfilters/MiscFilter/EdgeFixer.dll. GetLastError() returned 126. The file you tried to load or one of its dependencies is probably missing.

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 1946, in vapoursynth.vpy_evaluateScript
  File "src\cython\vapoursynth.pyx", line 1947, in vapoursynth.vpy_evaluateScript
  File "E:\Temp\TEMPPR~1.VPY", line 5, in <module>
    core.std.LoadPlugin(path="I:/Hybrid/64bit/vsfilters/MiscFilter/EdgeFixer.dll")
  File "src\cython\vapoursynth.pyx", line 1852, in vapoursynth.Function.__call__
vapoursynth.Error: Failed to load I:/Hybrid/64bit/vsfilters/MiscFilter/EdgeFixer.dll. GetLastError() returned 126. The file you tried to load or one of its dependencies is probably missing.
```
a. seeing that there have been a bunch of changes since the last release, would be nice if you could make a new release
b. list the dependencies of the filter
(using Win10pro 64bit here)

**Comment by sekrit-twc** [comment]
Did you load the right binary (32/64-bit)? EdgeFixer.dll has no dependencies. Also, the changes since r1 are not important (AVS+ support, 16-bit, typos).

**Comment by Selur** [comment]
I used the one from the x64-folder since I use 64bit Vapoursynth, just also tried the one in the x86-folder, error says the same.

**Comment by sekrit-twc** [comment]
Works for me. Issue must be with your system.

**Comment by Selur** [comment]
Which is why I asked about the dependencies.
From the looks of it the file isn't compiled statically and thus relies on some runtime or whatever dll and since it's nowhere mentioned what the .dll might rely on the only solution would be to blindly install and deinstall common dependencies which most people like to avoid.

**Comment by sekrit-twc** [comment]
You can use depends64.exe (http://www.dependencywalker.com/) if you believe that to be the case.

**Comment by Selur** [comment]
That shows tons of missing stuff,...
https://i.ibb.co/gVbtZtK/top.png
https://i.ibb.co/vsGgCFp/bottom.png
probably all belonging to some visual c++ runtime which needs to be installed,...
(I got Microsoft Visual C++ 2010, 2013 and 2017 installed, so my guess is that this belongs to 2015,...)

**Comment by sekrit-twc** [comment]
API-MS-WIN and EXT-MS-WIN are red herrings related to Windows Compatibility (https://stackoverflow.com/questions/36240215/dependency-walker-missing-dlls). I double-checked the project files, and EdgeFixer.dll is a statically-linked binary.

**Comment by Selur** [comment]
Okay,.... using Dependencies from https://github.com/lucasg/Dependencies shows all the dependencies present.
Which leaves me where I started with no clue why  I get the

>  Failed to load I:/Hybrid/64bit/vsfilters/MiscFilter/EdgeFixer.dll. GetLastError() returned 126. The file you tried to load or one of its dependencies is probably missing.

 error. I get the same error with vspipe and vseditor. (checked both to be sure it's not a vseditor bug)

**Comment by Selur** [comment]
Okay, I fixed it by:
a. copying the file to another folder
b. deleting the folder the filter was in
c. recreating the folder
d. copying back the file
-> no clue why it's working know, but it seems like this is somehow caused by my setup. (no clue what is causing it)
